# SPDX-FileCopyrightText: 2023 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

# This workflow will publish a Java project with Gradle
# For maven build see: https://github.com/marketplace/actions/gradle-build-action
# For maven publishing see: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

name: Publish Release

on:
  release:
    types: [published] # published instead of created because https://stackoverflow.com/a/61066906

jobs:
  publish-snapshot:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Releasing version ${{ github.event.release.tag_name }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.SIGNING_PASSWORD }}

      - name: Bump version
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}

      - name: Build & Publish to Maven Central
        run: mvn -U -B clean deploy -P release # -U: force updates for dependencies, -B: no user input, -P: profile
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
